### ISSUE TITLE
Creación de sección empresas

### ISSUE THREAD

**Issue by samuelsolis** [AsociacionDrupalES/asociaciondrupal#18]
El objetivo es tener un listado de empresas colaboradoras y una vista desplegada de cada una.

* Las empresas tienen que tener:
  - Título
  - Imagen
  - Descripción.
  - Casos de éxito -> Texto enriquecido.
  - Ofertas de empleo -> Texto enriquecido (igual, breve descripción y enlaces).

* Listado de empresas
  - Revisión de estilos y ver alguna cosilla

Dudas y sugerencias a Mon :P

**Comment by capynet** [comment]
Ya está funcionando en prod. Muchas gracias @samuelsolis por todo!
