### ISSUE TITLE
Añadir y configurar stage_file_proxy

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/asociaciondrupal#25]
https://www.drupal.org/project/stage_file_proxy

**Comment by capynet** [comment]
@plopesc creo que tenías experiencia con este módulo. Podrías hacer vos este issue cuando tengas un momento?

**Comment by DavidHernandez** [comment]
Pa' mi. Durante el sprint de mañana la hago.

**Comment by capynet** [comment]
Recuerda hacer estos cambios en la rama dev, que todo el mundo la ha liado en ese punto. Y gracias!
