### ISSUE TITLE
Habilitar cupones para socios nuevos para la dcamp 2015

### ISSUE THREAD

**Issue by capynet** [AsociacionDrupalES/asociaciondrupal#46]
Y antes de hacerlo mandar el cupon de descuento a todos los socios que sean 2014 2015 al dia de la fecha.

**Comment by capynet** [comment]
Me parece que esto queda en standby hasta que tengamos cupones en la web de la dcamp.

**Comment by DavidHernandez** [comment]
Tal vez podamos utilizar el módulo Views Send (https://www.drupal.org/project/views_send) para poder mandar los correos que necesitemos.

También podría utilizarse para la issue #47
