### ISSUE TITLE
No se envían los cupones a los socios cuando renuevan cuota

### ISSUE THREAD

**Issue by isholgueras** [AsociacionDrupalES/asociaciondrupal#55]
@capynet me ha comentado que no se envían los cupones de descuento a los que renuevan la cuota de socios del año 2016.

**Comment by isholgueras** [comment]
Me he montado el sitio en local y he visto que el componente de la regla de "Send coupons" tiene activado el Rol "Socio 2015". Imagino que será cambiando eso por "Socio 2016".

Existe una regla que añade el rol "Socio %year" cuando renuevas la cuota de socio, pero este año no renuevan la cuota de socio de 2015, así que imagino que será eso.

@capynet, no toco nada en producción. Te lo dejo a tí que cambies [el componente de la regla](http://asociaciondrupal.es/es/admin/config/workflow/rules/components/manage/rules_send_coupons/edit/2). Si no es esto me dices y sigo investigando.

![image](https://cloud.githubusercontent.com/assets/140742/13540555/8b3d714a-e257-11e5-8745-847841c930cb.png)

**Comment by capynet** [comment]
@isholgueras ese componente es para enviar el cupón "a mano". Es eierto que estaba desactualizado, y ya lo arreglé, pero este componente no se ejecuta en el proceso de compra. 

La regla que se ejecuta es es/admin/config/workflow/rules/reaction/manage/rules_send_coupon_dc2013_to_new_socio y ahí es donde se envía el correo (en teoría) que nunca llega a destino.

Ojo, tambien podria ser un problema del servidor de correos (just saying)

**Comment by capynet** [comment]
Como dato adicional, ejecuté el componente que comentaste y debería haberme llegado un correo a mi y a todos los socios, pero no ha llegado nada de nada. Empiezo a sospechar del servidor de correos.

**Comment by DavidHernandez** [comment]
Wait, wait. A mi si me ha llegado un correo.

**Comment by isholgueras** [comment]
A mí también me ha llegado.

**Comment by DavidHernandez** [comment]
Capy, ¿igual es porque no tienes el rol correcto?

**Comment by jsbalsera** [comment]
A mi también xD Sorry, capy, pero el servidor de correo te tiene manía xD
(O lo tienes en no deseado y no lo has mirado...)

2016-03-07 10:17 GMT+01:00 Ignacio Sánchez <notifications@github.com>:

> A mí también me ha llegado.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AsociacionDrupalES/asociaciondrupal/issues/55#issuecomment-193173789>
> .
>



-- 
Un saludo!

**Comment by capynet** [comment]
Perdón pues por el mail que os ha llegado. a mi no me llega nada y he revisado el correo y mi cuenta en la web.... Bueno, en un principio vuelve a pasar lo que la semana pasada, que algunos me decíanq ue funcionaba y cuando lo probaba no me llegaba. 

Voy a asumir que es un problema puntual de mi cuenta y cierro el issue.

@isholgueras mil gracias por llevar el tema!

**Comment by isholgueras** [comment]
¿Se puede ver un log de los correos enviados en el servidor de correo? Por comprobar si se envían o no.
